/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package summerproject;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;

/**
 *
 * @author SUJAL
 */
public class scrollprint extends javax.swing.JFrame {

    /**
     * Creates new form scrollprint
     */
    public scrollprint() {
        initComponents();
        getRecords();
    }

    
    public void getRecords()
    {
        try
        {
        Class.forName("com.mysql.jdbc.Driver");
        Connection con1 = DriverManager.getConnection("jdbc:mysql://localhost/hotelmanagementsystem","root","");
        PreparedStatement p1 = con1.prepareStatement("SELECT * FROM customerdatabase ORDER BY cid DESC LIMIT 1");
        ResultSet rs1 = p1.executeQuery();
        rs1.next();
        tname.setText(rs1.getString("name").toUpperCase());
        tarrivaltime.setText(rs1.getString("date"));
        tarrivaldate.setText(rs1.getString("time"));
        tnationality.setText(rs1.getString("nationality").toUpperCase());
        tarrival.setText(rs1.getString("arrival_from").toUpperCase());
        tpostaladdress.setText(rs1.getString("postal_address").toUpperCase());
        tphone.setText(rs1.getString("contact"));
        temail.setText(rs1.getString("email"));
        byte[] img = rs1.getBytes("photo");
        ImageIcon image = new ImageIcon(img);
        Image im = image.getImage();
        Image myimg = im.getScaledInstance(idlabel.getWidth(), idlabel.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon newimage = new ImageIcon(myimg);
        idlabel.setIcon(newimage);
        }
        catch(Exception re1)
        {
            re1.printStackTrace();
        }
        
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        printerpanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        txtname = new javax.swing.JLabel();
        txtnationality = new javax.swing.JLabel();
        txttel = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        tname = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel47 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel52 = new javax.swing.JLabel();
        tarrivaltime = new javax.swing.JLabel();
        tarrivaldate = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        tnationality = new javax.swing.JLabel();
        tpostaladdress = new javax.swing.JLabel();
        tphone = new javax.swing.JLabel();
        temail = new javax.swing.JLabel();
        tarrival = new javax.swing.JTextField();
        idlabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        printerpanel.setBackground(new java.awt.Color(255, 255, 255));
        printerpanel.setForeground(new java.awt.Color(51, 0, 102));
        printerpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 102));
        jLabel1.setText("HOTEL ATTIC EMPIRE");
        printerpanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 102));
        jLabel2.setText("Gyaneshwor, Kathmandu, Nepal");
        printerpanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 0, 102));
        jLabel3.setText("Tel: 0-4441140, 4441141");
        printerpanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo2.png"))); // NOI18N
        printerpanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 150, 110));

        jPanel3.setBackground(new java.awt.Color(51, 0, 102));
        jPanel3.setForeground(new java.awt.Color(51, 0, 102));
        jPanel3.setPreferredSize(new java.awt.Dimension(1180, 5));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1180, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        printerpanel.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 1180, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 0, 102));
        jLabel5.setText("GUEST REGISTER CARD");
        printerpanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 200, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 0, 102));
        jLabel6.setText("PLEASE WRITE IN BLOCK LETTER");
        printerpanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, -1, 20));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 0, 102));
        jLabel7.setText("MS/MR/MRS/MISS");
        printerpanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 0, 102));
        jLabel8.setText("ARRIVAL FROM");
        printerpanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 0, 102));
        jLabel9.setText("NATIONALITY");
        printerpanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 0, 102));
        jLabel10.setText("POSTAL ADDRESS");
        printerpanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 0, 102));
        jLabel11.setText("DATE OF BIRTH");
        printerpanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 500, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 0, 102));
        jLabel12.setText("TEL.NO. :(RES)");
        printerpanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 530, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 0, 102));
        jLabel13.setText("FACEBOOK ID");
        printerpanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 560, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 0, 102));
        jLabel14.setText("NOTE: YOU MAY DEPOSIT YOUR VALUABLES AT THE RECEPTION DESK.");
        printerpanel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 590, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 0, 102));
        jLabel15.setText("IF, LOST OR DAMAGED FROM THE ROOM, HOTEL WILL NOT HOLD ANY RESPONSIBILITY.");
        printerpanel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 620, -1, -1));
        printerpanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        jSeparator2.setForeground(new java.awt.Color(51, 0, 102));
        printerpanel.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 210, 10));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 0, 102));
        jLabel16.setText("ARRIVAL DATE:");
        printerpanel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 320, -1, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 0, 102));
        jLabel17.setText("ARRIVAL TIME:");
        printerpanel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 290, -1, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 0, 102));
        jLabel18.setText("PERSON:");
        printerpanel.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 260, -1, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 0, 102));
        jLabel19.setText("DEPARTURE DATE");
        printerpanel.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 380, -1, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 0, 102));
        jLabel20.setText("DEPARTURE TO");
        printerpanel.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 410, -1, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(51, 0, 102));
        jLabel21.setText("PASSPORT NO");
        printerpanel.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 440, -1, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(51, 0, 102));
        jLabel22.setText("MODE OF TRAVEL");
        printerpanel.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 500, -1, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(51, 0, 102));
        jLabel23.setText(" PURPOSE OF VISIT");
        printerpanel.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 530, -1, -1));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(51, 0, 102));
        jLabel24.setText("ENTRY POINT");
        printerpanel.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 410, -1, -1));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(51, 0, 102));
        jLabel25.setText(" PROFESSION");
        printerpanel.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 440, -1, -1));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(51, 0, 102));
        jLabel26.setText("OFFICE");
        printerpanel.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 530, -1, -1));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(51, 0, 102));
        jLabel27.setText("E-MAIL ADDRESS");
        printerpanel.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 560, -1, -1));

        jLabel31.setText(".........................................................................................................................................................................................................................................");
        printerpanel.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, 700, 10));

        jLabel32.setText("..............................................................................................................................................................................................................................................................................................................................................");
        printerpanel.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 480, 1010, 10));

        jLabel33.setText(".....................................................................................................................................");
        printerpanel.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, 400, 10));

        jLabel34.setText("..........................................................................................................................................................................................................................................................");
        printerpanel.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 510, 750, 10));

        jLabel35.setText(".....................................................................................................................................................................");
        printerpanel.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 570, 500, 10));

        jLabel36.setText("...........................................................................................................................................");
        printerpanel.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 450, 420, 10));

        jLabel37.setText(".....................................................................");
        printerpanel.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 450, 210, 10));

        jLabel38.setText(".........................................................................................................................................");
        printerpanel.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 540, 410, 10));

        jLabel39.setText(".........................................................................................................................................");
        printerpanel.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 570, 410, 10));

        jLabel40.setText("................................................................");
        printerpanel.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 450, 200, 10));

        jLabel41.setText(".................................................");
        printerpanel.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(1056, 300, 150, 10));

        jLabel43.setText(".............................................................");
        printerpanel.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 270, 190, 10));

        jLabel44.setText(".......................................................");
        printerpanel.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 390, 170, 10));

        jLabel45.setText(".............................................");
        printerpanel.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 540, 140, 10));

        jLabel46.setText(".............................................................");
        printerpanel.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 420, 190, 10));

        jLabel48.setText("............................................");
        printerpanel.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 510, 140, 10));

        jLabel49.setText(".................................................");
        printerpanel.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(1056, 330, 150, 10));

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel4.setOpaque(false);
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(51, 0, 102));
        jLabel28.setText("GUEST'S SIGNATURE");
        jPanel4.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(1392, 554, -1, -1));

        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel5.setOpaque(false);

        jLabel42.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(51, 0, 102));
        jLabel42.setText("REMEMBER DEAR GUESTS: ARRIVED BEFORE 12 NOON, CHECK OUR TIME 24 HOURS ");

        jLabel50.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(51, 0, 102));
        jLabel50.setText("ARRIVED AFTER 12 NOON, CHECK OUR TIME 12 HOURS");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(jLabel42))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(419, 419, 419)
                        .addComponent(jLabel50)))
                .addContainerGap(347, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel42)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel50)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 592, -1, -1));

        jLabel51.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(51, 0, 102));
        jLabel51.setText("RECEPTIONIST");
        jPanel4.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(1416, 740, -1, -1));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1392, 731, 157, -1));

        jSeparator3.setForeground(new java.awt.Color(51, 0, 102));
        jPanel4.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1386, 527, 150, 10));
        jPanel4.add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(847, 193, 702, -1));
        jPanel4.add(txtnationality, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 264, 425, -1));
        jPanel4.add(txttel, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 501, 425, -1));
        jPanel4.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(1024, 237, 229, 10));

        tname.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tname.setText("tname");
        jPanel4.add(tname, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 183, 698, -1));

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(997, 511, 130, 10));

        jLabel47.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(51, 0, 102));
        jLabel47.setText("GUEST'S SIGNATURE");
        jPanel4.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(997, 527, -1, -1));

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(999, 724, 130, 10));

        jLabel52.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(51, 0, 102));
        jLabel52.setText("RECEPTIONIST");
        jPanel4.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(1014, 740, -1, -1));

        tarrivaltime.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tarrivaltime.setText("tarrivaltime");
        jPanel4.add(tarrivaltime, new org.netbeans.lib.awtextra.AbsoluteConstraints(1001, 90, 145, -1));

        tarrivaldate.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tarrivaldate.setText("tarrivaldate");
        jPanel4.add(tarrivaldate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1001, 123, 145, -1));

        jLabel55.setText("........................................................................");
        jPanel4.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(626, 222, 215, 10));

        jLabel56.setText("..................................................................................................");
        jPanel4.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(587, 337, -1, -1));

        tnationality.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tnationality.setText("tnationality");
        tnationality.setFocusable(false);
        jPanel4.add(tnationality, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 237, 417, -1));

        tpostaladdress.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tpostaladdress.setText("tpostaladdress");
        jPanel4.add(tpostaladdress, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 270, 990, -1));

        tphone.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tphone.setText("tphone");
        jPanel4.add(tphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 332, 405, -1));

        temail.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        temail.setText("temail");
        jPanel4.add(temail, new org.netbeans.lib.awtextra.AbsoluteConstraints(655, 359, 472, -1));

        tarrival.setBackground(new java.awt.Color(255, 255, 255));
        tarrival.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tarrival.setForeground(new java.awt.Color(0, 0, 0));
        tarrival.setText("tarrival");
        tarrival.setBorder(null);
        jPanel4.add(tarrival, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 400, -1));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 7, 1166, 786));

        printerpanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 1180, 800));

        idlabel.setText("ID to be printed.....");
        printerpanel.add(idlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 1130, 870, 450));

        jScrollPane1.setViewportView(printerpanel);

        jButton1.setBackground(new java.awt.Color(102, 204, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jButton1.setText("Print");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 204, 255), 1, true));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1291, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(646, 646, 646)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 675, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        PrinterJob job = PrinterJob.getPrinterJob();
            job.setJobName("Print Data");
            
            job.setPrintable(new Printable()
            {
                public int print(Graphics pg,PageFormat pf, int pageNum)
                {
                    pf.setOrientation(PageFormat.PORTRAIT);
                    if(pageNum > 0)
                    {
                        return Printable.NO_SUCH_PAGE;
                    }
                
                    Graphics2D g2 = (Graphics2D)pg;
                    g2.translate(pf.getImageableX(), pf.getImageableY());
                    g2.scale(0.47,0.47);
                
                    printerpanel.print(g2);
         
               
                    return Printable.PAGE_EXISTS;
                         
                
                }
            });
            boolean ok = job.printDialog();
            if(ok)
            {
                try
                {
            
                    job.print();
                    dispose();
                    new reception();
                }
                catch (PrinterException ex)
                {
                    ex.printStackTrace();
                }
            }
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(scrollprint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(scrollprint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(scrollprint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(scrollprint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new scrollprint().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel idlabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JPanel printerpanel;
    private javax.swing.JTextField tarrival;
    private javax.swing.JLabel tarrivaldate;
    private javax.swing.JLabel tarrivaltime;
    private javax.swing.JLabel temail;
    private javax.swing.JLabel tname;
    private javax.swing.JLabel tnationality;
    private javax.swing.JLabel tphone;
    private javax.swing.JLabel tpostaladdress;
    private javax.swing.JLabel txtname;
    private javax.swing.JLabel txtnationality;
    private javax.swing.JLabel txttel;
    // End of variables declaration//GEN-END:variables
}
